version: '3.7'

x-json-logging: &json_logging
  driver: json-file
  options:
    max-size: '10m'
    max-file: '1'

services:
  redis:
    image: redis:6.0.8
    container_name: redis
    logging: *json_logging
    ports: ['6379:6379']

  postgres:
    image: postgres:12
    container_name: postgres
    logging: *json_logging
    ports: ['65432:5432']
    env_file: ./env/postgres.env
    volumes:
      - ./scripts/multiply-pg-db.sh:/docker-entrypoint-initdb.d/multiply-pg-db.sh
      - ./pgdata:/var/lib/postgresql/data/pgdata

  consul:
    image: consul:1.9.0
    container_name: consul
    logging: *json_logging
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"